. ~/.config/zsh/load_plugin.sh

# Lines configured by zsh-newuser-install
if [ -z "$DOCKER_WRAPPER_SERVER_HOSTNAME" ]; then
  HISTFILE=~/.histfile
else
  HISTFILE=~/.histfiles/$DOCKER_WRAPPER_SERVER_HOSTNAME
fi
HISTSIZE=10000
SAVEHIST=10000

bindkey -v
bindkey "^P" up-line-or-search
bindkey "^N" down-line-or-search

# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename "$HOME/.zshrc"

fpath=($HOME/.config/zsh/completions $fpath)

autoload -Uz compinit
compinit
# End of lines added by compinstall

### 補完侯補をメニューから選択する。
### select=2: 補完候補を一覧から選択する。補完候補が2つ以上なければすぐに補完する。
zstyle ':completion:*:default' menu select=2
### 補完候補がなければより曖昧に候補を探す。
### m:{a-z}={A-Z}: 小文字を大文字に変えたものでも補完する。
### r:|[._-]=*: 「.」「_」「-」の前にワイルドカード「*」があるものとして補完する。
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z} r:|[._-]=*'
#zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

#zstyle ':completion:*' keep-prefix
zstyle ':completion:*' recent-dirs-insert both

### 補完候補
### _oldlist 前回の補完結果を再利用する。
### _complete: 補完する。
### _match: globを展開しないで候補の一覧から補完する。
### _history: ヒストリのコマンドも補完候補とする。
### _ignored: 補完候補にださないと指定したものも補完候補とする。
### _approximate: 似ている補完候補も補完候補とする。
### _prefix: カーソル以降を無視してカーソル位置までで補完する。
zstyle ':completion:*' completer _oldlist _complete _match _history _ignored _approximate _prefix
#zstyle ':completion:*' completer _complete _ignored

## 補完候補をキャッシュする。
zstyle ':completion:*' use-cache yes
zstyle ':completion:*' cache-path ~/.zsh/cache
## 詳細な情報を使わない
zstyle ':completion:*' verbose no

setopt appendhistory autocd
setopt no_beep
setopt hist_ignore_dups   # 直前と同じコマンドラインはヒストリに追加しない
setopt hist_ignore_all_dups  # 重複したヒストリは追加しない
setopt hist_reduce_blanks
setopt hist_no_store
setopt hist_verify
setopt share_history  # シェルのプロセスごとに履歴を共有
setopt extended_history  # 履歴ファイルに時刻を記録
setopt append_history  # 複数の zsh を同時に使う時など history ファイルに上書きせず追加
setopt auto_list  # 補完候補が複数ある時に、一覧表示
setopt auto_menu  # 補完候補が複数あるときに自動的に一覧表示する
setopt no_flow_control
setopt print_eight_bit
setopt complete_in_word  # カーソル位置で補完する。
setopt glob
setopt glob_complete  # globを展開しないで候補の一覧から補完する。
setopt extended_glob  # 拡張globを有効にする。
setopt mark_dirs   # globでパスを生成したときに、パスがディレクトリだったら最後に「/」をつける。
setopt numeric_glob_sort  # 辞書順ではなく数字順に並べる。
setopt magic_equal_subst  # コマンドライン引数の --prefix=/usr とか=以降でも補完
setopt always_last_prompt  # 無駄なスクロールを避ける

PROMPT='%F{cyan}[%~]$%f '

zsh_title_precmd(){
  local title
  local pwd
  local project_root

  if [ -n "$APP_ROOT" ]; then
    title=$(basename "$APP_ROOT")
  else
    pwd=$(pwd)
    case "$pwd" in
      $HOME*)
        title=HOME
        ;;
      *)
        if [ -z "$DOCKER_WRAPPER_SERVER_HOSTNAME" ]; then
          title=GLOBAL
        else
          project_root=/apps/${DOCKER_WRAPPER_SERVER_HOSTNAME//-/\/}
          case "$pwd" in
            ${project_root}*)
              title=${pwd#$project_root}
              if [ -z "$title" ]; then
                title=$DOCKER_WRAPPER_SERVER_HOSTNAME
              fi
              ;;
          esac
        fi
        ;;
    esac
  fi

  print -n "\ek$title\e\\"
}

autoload -Uz add-zsh-hook
add-zsh-hook precmd zsh_title_precmd

export LANG=ja_JP.UTF-8

if [ -f /etc/labo-env ]; then
  eval "$(cat /etc/labo-env | grep '^\(DOCKER_HOST=\|DOCKER_WRAPPER_\|LABO_\)' | sed 's/^/export /')"
fi

export PATH=/usr/bin:/usr/local/bin:$HOME/bin:$PATH
export RAILS_DEVEL_NAME=$(basename $HOME)


# alias
alias vi='nvim'

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

alias ls='ls --color=auto'
alias ll='ls -l'
alias la='ls -Al'
alias lA='ls -al'

alias grep='grep --color=auto'

alias s='git status-verbose'
alias a='git add -A'
alias ci='git commit -m'
alias br='git branch-and-post'
alias rr='git release-request'
alias rt='git purge; git release-tag'
alias p='git pub'
alias post='git pub && git post'

alias clear-zcompdump='rm -f ~/.zcompdump ~/.zplug/zcompdump'

# docker-wrapper
. docker-wrapper.rc.env
