[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-fugitive']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
let g:airline_theme='base16_railscasts'
'''

[[plugins]]
repo = 'vim-scripts/Railscasts-Theme-GUIand256color'
hook_add = '''
colorscheme railscasts
'''

[[plugins]]
repo = 'kassio/neoterm'
