[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim', 'neoyank.vim']
hook_add = '''
nnoremap <silent> <SPACE>k :Denite file/rec<CR>
nnoremap <silent> <SPACE>l :Denite file/rec/git<CR>
nnoremap <silent> <SPACE>b :Denite buffer<CR>
nnoremap <silent> <SPACE>z :Denite file_mru<CR>
nnoremap <silent> <SPACE>g :DeniteBufferDir grep -buffer-name=search-buffer-denite<CR>
nnoremap <silent> <SPACE>f :Denite -resume -buffer-name=search-buffer-denite<CR>
nnoremap <silent> <SPACE>n :Denite -resume -buffer-name=search-buffer-denite -select=+1 -immediately<CR>
nnoremap <silent> <SPACE>p :Denite -resume -buffer-name=search-buffer-denite -select=-1 -immediately<CR>

call denite#custom#var('file/rec', 'command', ['rg', '--files'])
call denite#custom#var('grep', 'command', ['rg', '--threads', '1'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'final_opts', [])
call denite#custom#var('grep', 'separator', ['--'])
call denite#custom#var('grep', 'default_opts', ['-i', '--vimgrep', '--no-heading'])

call denite#custom#map('insert', '<C-n>', '<denite:move_to_next_line>', 'noremap')
call denite#custom#map('insert', '<C-p>', '<denite:move_to_previous_line>', 'noremap')

call denite#custom#map('normal', 'D', '<denite:multiple_mappings:denite:toggle_select_all,denite:do_action:delete>', 'noremap')

call denite#custom#alias('source', 'file/rec/git', 'file/rec')
call denite#custom#var('file/rec/git', 'command', ['git', 'ls-files', '-co', '--exclude-standard'])
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-fugitive']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = ['vim-airline']
hook_add = '''
au VimEnter * nested AirlineTheme vice
'''

[[plugins]]
repo = 'marcopaganini/mojave-vim-theme'
hook_add = '''
set termguicolors
au VimEnter * nested colorscheme mojave
'''

[[plugins]]
repo = 'kassio/neoterm'

[[plugins]]
repo = 'raichoo/purescript-vim'

[[plugins]]
repo = 'elixir-lang/vim-elixir'

[[plugins]]
repo = 'lambdatoast/elm.vim'

[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = '''
let g:rustfmt_autosave = 0
'''
