[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim', 'neoyank.vim']
hook_add = '''
nnoremap <silent> ,a :<C-u>Denite file_rec<CR>
nnoremap <silent> ,b :<C-u>Denite buffer -mode=normal<CR>
nnoremap <silent> ,f :<C-u>DeniteBufferDir file_rec<CR>
nnoremap <silent> ,g :<C-u>Denite grep<CR>
nnoremap <silent> ,z :<C-u>Denite file_mru<CR>
nnoremap <silent> ,v :<C-u>Denite neoyank -mode=normal<CR>
nnoremap <silent> ,r :<C-u>Denite command_history -mode=normal<CR>
nnoremap <silent> L :<C-u>DeniteCursorWord line -mode=normal<CR>
nnoremap <silent> K :<C-u>DeniteCursorWord grep -mode=normal<CR>
nnoremap <silent> <C-f> :<C-u>Denite -resume<CR>
nnoremap <silent> <C-p> :<C-u>Denite -resume -immediately -select=-1<CR>
nnoremap <silent> <C-n> :<C-u>Denite -resume -immediately -select=+1<CR>
call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
call denite#custom#var('grep', 'command', ['ag'])
call denite#custom#var('grep', 'default_opts', ['-i', '--vimgrep'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', [])
call denite#custom#var('grep', 'separator', ['--'])
call denite#custom#var('grep', 'final_opts', [])
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-fugitive']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = ['vim-airline']
hook_add = '''
au VimEnter * nested AirlineTheme behelit
'''

[[plugins]]
repo = 'vim-scripts/Railscasts-Theme-GUIand256color'
hook_add = '''
au VimEnter * nested colorscheme railscasts
'''

[[plugins]]
repo = 'kassio/neoterm'

[[plugins]]
repo = 'raichoo/purescript-vim'

[[plugins]]
repo = 'elixir-lang/vim-elixir'

[[plugins]]
repo = 'lambdatoast/elm.vim'
