[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['vim-fugitive']

[[plugins]]
repo = 'vim-scripts/Railscasts-Theme-GUIand256color'
hook_add = '''
colorscheme railscasts
'''

[[plugins]]
repo = 'kassio/neoterm'

[[plugins]]
repo = 'raichoo/purescript-vim'

[[plugins]]
repo = 'elixir-lang/vim-elixir'

[[plugins]]
repo = 'lambdatoast/elm.vim'
