[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim', 'neoyank.vim']
hook_add = '''
map ,a :Denite file_rec<CR>
map ,b :Denite buffer -mode=normal<CR>
map ,f :DeniteBufferDir file_rec<CR>
map ,g :Denite grep<CR>
map ,z :Denite file_mru<CR>
map ,v :Denite neoyank -mode=normal<CR>
map ,r :Denite command_history -mode=normal<CR>
map L :DeniteCursorWord line -mode=normal<CR>
map K :DeniteCursorWord grep -mode=normal<CR>
map <C-F> :Denite -resume<CR>
map <C-P> :Denite -resume -immediately -select=-1<CR>
map <C-N> :Denite -resume -immediately -select=+1<CR>
'''
hook_post_source = '''
call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
call denite#custom#var('grep', 'command', ['ag'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', [])
call denite#custom#var('grep', 'default_opts', ['--follow', '--no-group', '--no-color'])
call denite#custom#filter('matcher_ignore_globs', 'ignore_globs', [ '*~', '*.o', '*.exe', '*.bak', '.DS_Store', '*.pyc', '*.sw[po]', '*.class', '.hg/', '.git/', '.bzr/', '.svn/', 'tags', 'tags-*', 'vendor/', 'node_modules/', 'deps/', '_build/' ])
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['vim-fugitive']

[[plugins]]
repo = 'vim-scripts/Railscasts-Theme-GUIand256color'
hook_add = '''
colorscheme railscasts
'''

[[plugins]]
repo = 'kassio/neoterm'

[[plugins]]
repo = 'raichoo/purescript-vim'

[[plugins]]
repo = 'elixir-lang/vim-elixir'

[[plugins]]
repo = 'lambdatoast/elm.vim'
