[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim', 'neoyank.vim']
hook_add = '''
nnoremap <silent> <SPACE>p :Denite file/rec<CR>
nnoremap <silent> <SPACE>l :Denite file/rec/git<CR>
nnoremap <silent> <SPACE>b :Denite buffer<CR>
nnoremap <silent> <SPACE>z :Denite file_mru<CR>

call denite#custom#var('file/rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])

call denite#custom#var('grep', 'command', ['ag'])
call denite#custom#var('grep', 'default_opts', ['-i', '--vimgrep'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', [])
call denite#custom#var('grep', 'separator', ['--'])
call denite#custom#var('grep', 'final_opts', [])

call denite#custom#alias('source', 'file/rec/git', 'file/rec')
call denite#custom#var('file/rec/git', 'command', ['git', 'ls-files', '-co', '--exclude-standard'])

autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
  nnoremap <silent><buffer><expr> d denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> q denite#do_map('quit')
  nnoremap <silent><buffer><expr> a denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> u denite#do_map('move_up_path')
endfunction

autocmd FileType denite-filter call s:denite_filter_my_settings()
function! s:denite_filter_my_settings() abort
  imap <silent><buffer> <C-o> <Plug>(denite_filter_quit)<CR>
endfunction
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-fugitive']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = ['vim-airline']
hook_add = '''
au VimEnter * nested AirlineTheme vice
'''

[[plugins]]
repo = 'marcopaganini/mojave-vim-theme'
hook_add = '''
set termguicolors
au VimEnter * nested colorscheme mojave
'''
